// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {notes} from '../models';

export function CreateNote(arg1:string,arg2:string):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function GetNotes():Promise<Array<notes.Note>>;

export function UpdateNoteContent(arg1:number,arg2:string):Promise<void>;

export function UpdateNoteTitle(arg1:number,arg2:string):Promise<void>;
